### ISSUE TITLE
N_B4 nicht nachvollziehbar

### ISSUE THREAD

**Issue by grayoctagon** [pschatzmann/stm32f411-i2s#1]
there are some points(e.g. in [README.md](https://github.com/pschatzmann/stm32f411-i2s/tree/main#readme) ) where a variable or definition "N_B4" is used, but I could not find where it is defined. (search: https://github.com/search?q=repo%3Apschatzmann%2Fstm32f411-i2s+N_B4&type=code ) 
can you please make a comment which frequency is meant? 
e.g.: "//N_B4 is from libary123 and is the default frequency 4 which results in 20Hz"

**Comment by pschatzmann** [comment]
N_B4 is part of the AudioTools which automatically includes the MusicalNotes.h
